name: Main
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - run: pip install poetry
    - run: poetry install
    - run: poetry run flake8
    - run: rtd-redirects --help
